name: Trigger auto deployment for container-app-7dh7zsoopfyes

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'fastify-api-server/**'
    - '.github/workflows/container-app-7dh7zsoopfyes-AutoDeployTrigger-2c651c89-974b-4750-b72e-c86384cf8a63.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP7DH7ZSOOPFYES_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP7DH7ZSOOPFYES_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP7DH7ZSOOPFYES_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/fastify-api-server 
          registryUrl: defaultacrcontainerregistrybf0a.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPP7DH7ZSOOPFYES_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP7DH7ZSOOPFYES_REGISTRY_PASSWORD }}
          containerAppName: container-app-7dh7zsoopfyes
          resourceGroup: shopathomesvelteafd39926
          imageToBuild: defaultacrcontainerregistrybf0a.azurecr.io/container-app-7dh7zsoopfyes:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


